/**
 * Report exports: CSV and XLSX, generated on the server and streamed.
 *
 * SHEETJS IS REUSED, NOTHING IS ADDED. `xlsx` has been in package.json since
 * phase 17, where it reads the sales order and purchase order extracts. This
 * writes with the same library.
 *
 * A USER GAINS NOTHING BY EXPORTING. The rows come from the report's own
 * `run`, which called the metric service, which applied the caller's scope
 * and their field-level restrictions. There is no second query with a looser
 * population anywhere in this file. The credit column is absent from a
 * caller's export for exactly the same reason it is absent from their screen:
 * the service never produced it.
 *
 * FORMULA INJECTION IS DEFUSED IN BOTH FORMATS, and it has to be, because a
 * customer name and a case subject are user-entered text. `=cmd|calc` typed
 * into a customer record and exported to a spreadsheet is a remote command on
 * whoever opens it, and the fact that we did not type it is no defence.
 *
 * ZERO AND UNKNOWN STAY DIFFERENT. A null cell is empty in both formats and
 * never becomes 0, because "we have no invoice timestamp for this order" and
 * "this order took no time to invoice" are different statements and only one
 * of them is ever true.
 */
import * as XLSX from 'xlsx';
import type { ReportDefinition, ReportRun, CellValue } from './catalogue.ts';
import type { AnalyticsFilter } from '../analytics/filters.ts';
import { auditEventStmt, type Stmt } from '../repos/authRecords.ts';

/** The characters a spreadsheet treats as the start of a formula. */
const FORMULA_START = /^[=+\-@\t\r]/;

/**
 * One cell as CSV. Identical rule to the phase 20 exporter, which this
 * matches deliberately rather than importing, because that one is shaped for
 * its own header row; the escaping itself is the same three lines and is
 * asserted equal by a test.
 */
export function csvCell(value: CellValue): string {
  if (value === null || value === undefined) return '';
  const raw = String(value);
  const defused = FORMULA_START.test(raw) ? `'${raw}` : raw;
  return `"${defused.replace(/"/g, '""')}"`;
}

/**
 * The same defusing for a spreadsheet cell.
 *
 * A NUMBER STAYS A NUMBER. Quoting every cell would make a workbook of text
 * that nobody can sum, which defeats the point of exporting to XLSX. So only
 * strings are inspected, and a numeric cell is written as a number.
 */
export function sheetCell(value: CellValue): XLSX.CellObject {
  if (value === null || value === undefined) return { t: 's', v: '' };
  if (typeof value === 'number') return { t: 'n', v: value };
  const raw = String(value);
  return { t: 's', v: FORMULA_START.test(raw) ? `'${raw}` : raw };
}

export interface ExportMetadata {
  reportName: string;
  generatedAt: string;
  generatedBy: string;
  filters: string;
  dateBasis: string;
  dataFreshness: string;
  rowCount: number;
}

/**
 * The filter in one readable line.
 *
 * Every non-null field, named. An export somebody prints and takes to a
 * meeting has to be able to say what it is a view of, and "sales orders,
 * August" is not enough when the question is which affiliate.
 */
export function describeFilter(filter: AnalyticsFilter): string {
  const parts: string[] = [];
  parts.push(
    filter.from === null && filter.to === null
      ? 'all dates'
      : `${filter.from ?? 'no start'} to ${filter.to ?? 'no end'}`,
  );
  const named: [string, string | null][] = [
    ['country', filter.countryId],
    ['affiliate', filter.affiliateId],
    ['business unit', filter.businessUnitId],
    ['customer', filter.accountId],
    ['product group', filter.productGroupId],
    ['product', filter.productId],
    ['owner', filter.ownerId],
    ['team', filter.teamId],
    ['currency', filter.currency],
    ['status', filter.status],
  ];
  for (const [label, value] of named) {
    if (value !== null && value !== '') parts.push(`${label} ${value}`);
  }
  parts.push(`minimum volume ${filter.minVolume}`);
  return parts.join('; ');
}

/**
 * The metadata block that heads every export.
 *
 * IT IS A COMMENT BLOCK IN CSV AND A SHEET IN XLSX, not extra columns beside
 * the data, so a reader can delete it or a script can skip it without
 * disturbing the rows. What it must never do is alter a business value to
 * make the file tidy, and it does not: it sits above the data and changes
 * nothing in it.
 */
function metadataLines(meta: ExportMetadata, kpis: ReportDefinition['kpis']): string[][] {
  const lines: string[][] = [
    ['Report', meta.reportName],
    ['Generated at (UTC)', meta.generatedAt],
    ['Generated by', meta.generatedBy],
    ['Filters', meta.filters],
    ['Date basis', meta.dateBasis],
    ['Data freshness', meta.dataFreshness],
    ['Rows', String(meta.rowCount)],
    [],
    ['KPI', 'Definition', 'Denominator', 'Date basis'],
  ];
  for (const kpi of kpis) {
    lines.push([kpi.name, kpi.definition, kpi.denominator, kpi.dateBasis]);
  }
  lines.push([]);
  return lines;
}

export function toCsv(report: ReportDefinition, run: ReportRun, meta: ExportMetadata): string {
  const lines: string[] = [];
  for (const row of metadataLines(meta, report.kpis)) {
    lines.push(row.length === 0 ? '' : `# ${row.map(csvCell).join(',')}`);
  }
  for (const note of run.notes) lines.push(`# ${csvCell(note)}`);
  lines.push('');
  lines.push(run.columns.map((column) => csvCell(column.label)).join(','));
  for (const row of run.rows) {
    lines.push(run.columns.map((column) => csvCell(row[column.key] ?? null)).join(','));
  }
  return lines.join('\n');
}

/**
 * The workbook: one sheet of data and one of provenance.
 *
 * Two sheets rather than a preamble on the data sheet, because a preamble
 * breaks every formula, filter and pivot somebody builds over the rows, and
 * the whole reason to export XLSX rather than CSV is that they intend to do
 * exactly that.
 */
export function toXlsx(report: ReportDefinition, run: ReportRun, meta: ExportMetadata): Uint8Array {
  const workbook = XLSX.utils.book_new();

  const header: XLSX.CellObject[] = run.columns.map((column) => ({
    t: 's',
    v: column.label,
  }));
  const body = run.rows.map((row) =>
    run.columns.map((column) => sheetCell(row[column.key] ?? null)),
  );
  // Built cell by cell rather than through `aoa_to_sheet` on raw values,
  // because that helper infers each cell's type from the value and would
  // undo the defusing above: a string beginning with `=` would go back to
  // being a formula.
  const dataSheet: XLSX.WorkSheet = {};
  const grid: XLSX.CellObject[][] = [header, ...body];
  const range = { s: { r: 0, c: 0 }, e: { r: grid.length - 1, c: run.columns.length - 1 } };
  for (let r = 0; r < grid.length; r += 1) {
    const rowCells = grid[r] as XLSX.CellObject[];
    for (let c = 0; c < run.columns.length; c += 1) {
      const cell = rowCells[c] ?? { t: 's', v: '' };
      // An empty string cell is omitted entirely, which is how a spreadsheet
      // represents "no value". Writing '' would give a blank that counts as
      // populated, and the difference matters to COUNTA.
      if (cell.t === 's' && cell.v === '') continue;
      dataSheet[XLSX.utils.encode_cell({ r, c })] = cell;
    }
  }
  dataSheet['!ref'] = XLSX.utils.encode_range(range);
  XLSX.utils.book_append_sheet(workbook, dataSheet, 'Data');

  const about = metadataLines(meta, report.kpis);
  about.push([], ['Notes'], ...run.notes.map((note) => [note]));
  const aboutSheet = XLSX.utils.aoa_to_sheet(
    about.map((row) => row.map((cell) => (FORMULA_START.test(cell) ? `'${cell}` : cell))),
  );
  XLSX.utils.book_append_sheet(workbook, aboutSheet, 'About this export');

  // `type: 'array'` yields an ArrayBuffer. It is wrapped rather than cast,
  // because a cast would compile and the caller would then index into
  // something with no indices, which is a runtime nothing rather than a
  // type error.
  return new Uint8Array(XLSX.write(workbook, { type: 'array', bookType: 'xlsx' }) as ArrayBuffer);
}

/** A filename that says what the file is without a reader opening it. */
export function exportFilename(
  report: ReportDefinition,
  filter: AnalyticsFilter,
  ext: string,
): string {
  const range =
    filter.from === null && filter.to === null
      ? 'all-dates'
      : `${filter.from ?? 'start'}-to-${filter.to ?? 'end'}`;
  return `${report.id}-${range}.${ext}`;
}

/**
 * The ceiling on one export, and the reason it refuses rather than truncates.
 *
 * There is no queue and no Cloudflare binding this batch may add, so an
 * export either completes inside one request or it does not happen. Given
 * that, the dangerous outcome is a truncated file: it looks complete,
 * somebody sums it, and the total is wrong with nothing on the page to say
 * so. So the endpoint refuses above this and says what to narrow.
 *
 * Twenty thousand rows is comfortably above every report in the catalogue on
 * real Hass volumes (the largest, the sales order detail, is 662 documents on
 * the real extract) and comfortably below what would exhaust an isolate.
 */
export const MAX_EXPORT_ROWS = 20000;

/**
 * The audit row for a report export. Filters, count and format, never the
 * content.
 *
 * `entity_type` is REPORT and `entity_id` is the report id, so the trail can
 * answer "who has been exporting the approver performance report" without
 * carrying a copy of what they exported.
 */
export function reportExportStmt(input: {
  actorUserId: string;
  report: ReportDefinition;
  filter: AnalyticsFilter;
  rowCount: number;
  format: string;
  ip: string | null;
  userAgent: string | null;
  now: Date;
}): Stmt {
  return auditEventStmt({
    actorUserId: input.actorUserId,
    eventType: REPORT_EXPORT_EVENT,
    entityType: 'REPORT',
    entityId: input.report.id,
    action: 'EXPORT',
    beforeJson: null,
    afterJson: JSON.stringify({
      reportName: input.report.name,
      reportType: input.report.family,
      filters: describeFilter(input.filter),
      rowCount: input.rowCount,
      format: input.format,
    }),
    ip: input.ip,
    userAgent: input.userAgent,
    now: input.now,
  }) as Stmt;
}

export const REPORT_EXPORT_EVENT = 'REPORT_EXPORTED';
