// Generate the typed column layer (grc/db/columns.ts) from the ground-truth
// dictionary (grc/db/schema.md). Run: node grc/db/gen-columns.mjs
//
// The dictionary is the live hassaudit schema; the generated module binds every
// GRC query's column names to it, so a misspelt or non-existent column fails
// `pnpm build` instead of the user's screen. Edit schema.md, regenerate, commit
// both. This is a build-time dev tool and ships nothing to the Worker.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const outFile = join(here, '..', '..', 'src', 'lib', 'grc', 'schema', 'columns.ts');
const schema = readFileSync(join(here, 'schema.md'), 'utf8');

// Each table is one line: `- **table_name**: col1, col2, col3`.
const rowRe = /^- \*\*([a-z_][a-z0-9_]*)\*\*:\s*(.+?)\s*$/;
const tables = [];
for (const line of schema.split('\n')) {
  const m = rowRe.exec(line);
  if (!m) continue;
  const name = m[1];
  const columns = m[2]
    .split(',')
    .map((c) => c.trim())
    .filter(Boolean);
  if (columns.length === 0) throw new Error(`table ${name} has no columns`);
  const seen = new Set();
  for (const c of columns) {
    if (!/^[a-z_][a-z0-9_]*$/.test(c)) throw new Error(`bad column name ${name}.${c}`);
    if (seen.has(c)) throw new Error(`duplicate column ${name}.${c}`);
    seen.add(c);
  }
  tables.push({ name, columns });
}
tables.sort((a, b) => a.name.localeCompare(b.name));

const body = tables
  .map((t) => {
    const cols = t.columns.map((c) => `    ${c}: '${c}',`).join('\n');
    return `  ${t.name}: {\n${cols}\n  },`;
  })
  .join('\n');

const out = `// GENERATED by grc/db/gen-columns.mjs from grc/db/schema.md. Do not edit by hand.
//
// The typed column layer binds GRC queries to the live hassaudit schema. Take
// every column name from here (via \`cols()\` or \`C.<table>.<column>\`): a column
// that does not exist on the table is a compile error, so a wrong name fails
// \`pnpm build\` rather than 500ing at runtime. The full-text-search tables are
// excluded on purpose; query them only through FTS MATCH helpers.

export const C = {
${body}
} as const;

export type Schema = typeof C;
export type TableName = keyof Schema;
export type ColumnOf<T extends TableName> = keyof Schema[T];

/**
 * Alias-qualify a table's typed columns for use in a SQL string. The result has
 * exactly the table's columns as keys, so a typo or a non-existent column is a
 * compile error; each value is the column name, prefixed with the alias when one
 * is given, e.g. \`cols(C.work_papers, 'wp').work_paper_ref === 'wp.work_paper_ref'\`.
 */
export function cols<T extends Record<string, string>>(
  table: T,
  alias?: string,
): { readonly [K in keyof T]: string } {
  const prefix = alias ? \`\${alias}.\` : '';
  const out: Record<string, string> = {};
  for (const key of Object.keys(table)) out[key] = \`\${prefix}\${table[key]}\`;
  return out as { readonly [K in keyof T]: string };
}
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, out);
console.log(`Generated ${outFile} for ${tables.length} tables.`);
